### ISSUE TITLE
 dashboard page

### ISSUE THREAD

**Issue by costargc** [costargc/fortsaet#11]
FrontEnd: work on the dashboard page (once user submits the data in the homepage - user will be redirected to the dashboard page. As our data is a discrete data we would need something like bar charts and pizza graphs (or maybe sunburst).

Review github for already done dashboards (order by amount of stars are always a good way to go). Also, we would need to explore chart.js to build the graphs in JS.

![image](https://user-images.githubusercontent.com/25669140/58998798-a86a5900-87d0-11e9-89cd-ffcb22450550.png)

ref.: http://experception.net/Franconeri_ExperCeptionDotNet_DataVisQuickRef.pdf

## acceptance criteria

- [ ] define mock up in JS  
- [ ] check chart.js to build the charts

**Comment by brianmringo** [comment]
I am on this now

**Comment by brianmringo** [comment]
I actually think this is a different area where we can use an additional API. Google charts is free.  and looks pretty nice.
